import Head from 'next/head'
import { useEffect } from 'react'
import { useRouter } from 'next/router'
import { GetLanguageContext } from '../context/LanguageContext'
import Hero from '../components/home/Hero/Hero'
import ExhibitorsSection from '../components/home/ExhibitorsSection/ExhibitorsSection'
import Rest from '../components/home/Rest/Rest'
import ReviewSection from '../components/home/ReviewsSection/ReviewSection'
import ImageGallery from '../components/home/ImageGallery/ImageGallery'
import MediaSponsorsSection from '../components/home/MediaSponsorsSection/MediaSponsorsSection'
import SponsorsSection from '../components/home/SponsorsSection/SponsorsSection'
import TicketsSection from '../components/ticketsSection/TicketsSection'
import FloatingButton from '../components/floatingButton/FloatingButton'
import Exhibition from '../components/home/Exhibition/Exhibition'
import ForExhibitors from '../components/home/ForExhibitors/ForExhibitors'
import MediaReviews from '../components/home/MediaReviews/MediaReviews'
import Speakers from '../components/home/Speakers/Speakers'
import Location from '../components/home/Location/Location'

export default function Home() {

  const { locale } = useRouter()
  const { language, setLanguage } = GetLanguageContext()

  useEffect(() => {

    setLanguage({
      ...language,
      locale: locale
    })
  }, [locale])

  return (
    <div>
      <Head>
        <title>Mary Jane Berlin - Cannabis Expo Germany | Festival | Conference</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Hero />
      <Exhibition />
      <ForExhibitors />
      <MediaReviews />
      <ExhibitorsSection />
      <Rest />
      <SponsorsSection />
      <MediaSponsorsSection />
      <Speakers />
      <ReviewSection />
      <ImageGallery />
      <TicketsSection />
      <Location />
      <FloatingButton />
    </div>
  )
}