import Head from 'next/head'
// import { GetContentContext } from '../context/ContentContext'
import { GetLanguageContext } from '../context/LanguageContext'
import Hero from '../components/home/Hero/Hero'
// import Rest from '../components/home/Rest/Rest'
// import ReviewSection from '../components/home/ReviewsSection/ReviewSection'
// import ImageGallery from '../components/home/ImageGallery/ImageGallery'
// import MediaSponsorsSection from '../components/home/MediaSponsorsSection/MediaSponsorsSection'
// import SponsorsSection from '../components/home/SponsorsSection/SponsorsSection'
// import TicketsSection from '../components/ticketsSection/TicketsSection'
// import FloatingButton from '../components/floatingButton/FloatingButton'
import Exhibition from '../components/home/Exhibition/Exhibition'
import ExhibitorsSection from '../components/home/ExhibitorsSection/ExhibitorsSection'
// import ForExhibitors from '../components/home/ForExhibitors/ForExhibitors'
// import MediaReviews from '../components/home/MediaReviews/MediaReviews'
// import Speakers from '../components/home/Speakers/Speakers'
// import Location from '../components/home/Location/Location'

export default function Home({ data }) {


  return (
    <div>
      <Head>
        <title>Mary Jane Berlin - Cannabis Expo Germany | Festival | Conference</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Hero data={data.hero} />
      {/* <Exhibition /> */}
      {/* <ForExhibitors /> */}
      {/* <MediaReviews /> */}
      {/* <ExhibitorsSection /> */}
      {/* <Rest /> */}
      {/* <SponsorsSection /> */}
      {/* <MediaSponsorsSection /> */}
      {/* <Speakers /> */}
      {/* <ReviewSection /> */}
      {/* <ImageGallery /> */}
      {/* <TicketsSection /> */}
      {/* <Location /> */}
      {/* <FloatingButton /> */}
    </div>
  )
}


export async function getServerSideProps(context) {

  const res = await fetch('https://b3ta40.myraidbox.de/graphql', {
    method: "POST",
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({
      query: `
      query NewQuery {
        pages(where: {id: 2}) {
          edges {
            node {
              hero {
                subtitleEn
                dateEn
                monthEn
                yearEn
                subtitleDe
                dateDe
                monthDe
                yearDe
                counterDaysDe
                counterDaysEn
                counterHoursEn
                counterMinutesEn
                ctaEn
                counterHoursDe
                counterMinutesDe
                counterSecondsDe
                counterSecondsEn
                ctaDe
                ctaUrl
              }
            }
          }
        }
      }
      `
    })
  })

  const json = await res.json()

  // const data = {
  //   en: {
  //     home: {
  //       titleDate: json.data.pageHome.nodes[0].heroTitleDate,
  //       titleMonth: json.data.pageHome.nodes[0].heroTitleMonth,
  //     }
  //   },
  //   de:{
  //     home: {
  //       titleDate: json.data.pageHome.nodes[1].heroTitleDate,
  //       titleMonth: json.data.pageHome.nodes[1].heroTitleMonth,
  //     }
  //   }
  // }

  return {
    props: {
      // data: json.data.pageHome.nodes
      data: json.data.pages.edges[0].node
    }
  }
}